export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_ALBUMS = 'FETCH_ALBUMS'
export const REMOVE_ALBUM = 'REMOVE_ALBUM'
export const POST_ALBUM = 'POST_ALBUM'
export const POST_PHOTO = 'POST_PHOTO'
export const ALBUM_DETAILS = 'ALBUM_DETAILS'
